//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registro_mockup.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("registro_mockup.Idiomas.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sesión no se puede abrir.
        /// </summary>
        internal static string AbrirSesionError {
            get {
                return ResourceManager.GetString("AbrirSesionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer Contraseña.
        /// </summary>
        internal static string AsuntoCorreo {
            get {
                return ResourceManager.GetString("AsuntoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion CortoHistoria.
        /// </summary>
        internal static string btnAC {
            get {
                return ResourceManager.GetString("btnAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Libro.
        /// </summary>
        internal static string btnAgregarLibroAdmin {
            get {
                return ResourceManager.GetString("btnAgregarLibroAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Usuario.
        /// </summary>
        internal static string btnAgregarUsuarioAdmin {
            get {
                return ResourceManager.GetString("btnAgregarUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion Libro.
        /// </summary>
        internal static string btnAL {
            get {
                return ResourceManager.GetString("btnAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AÑADIR AL CARRITO.
        /// </summary>
        internal static string btnAñadirCarrito {
            get {
                return ResourceManager.GetString("btnAñadirCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion Usuario.
        /// </summary>
        internal static string btnAU {
            get {
                return ResourceManager.GetString("btnAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borradores.
        /// </summary>
        internal static string btnBorradoresCortohistorias {
            get {
                return ResourceManager.GetString("btnBorradoresCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btnBorrar {
            get {
                return ResourceManager.GetString("btnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscarCortohistoria {
            get {
                return ResourceManager.GetString("btnBuscarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscarLibro {
            get {
                return ResourceManager.GetString("btnBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string btnBuscarUsuario {
            get {
                return ResourceManager.GetString("btnBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string btnCargarAgregarLibro {
            get {
                return ResourceManager.GetString("btnCargarAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnCargarEditarLibro {
            get {
                return ResourceManager.GetString("btnCargarEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string btnCargarImagenCortohistoria {
            get {
                return ResourceManager.GetString("btnCargarImagenCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string btnCargarImagenEditarUsuario {
            get {
                return ResourceManager.GetString("btnCargarImagenEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string btnCargarMiCuenta {
            get {
                return ResourceManager.GetString("btnCargarMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPRAR AHORA.
        /// </summary>
        internal static string btnComprarAhora {
            get {
                return ResourceManager.GetString("btnComprarAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Edición.
        /// </summary>
        internal static string btnConfirmarEdicionMiCuenta {
            get {
                return ResourceManager.GetString("btnConfirmarEdicionMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string btnContinuar {
            get {
                return ResourceManager.GetString("btnContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistorias.
        /// </summary>
        internal static string btnCortohistorias {
            get {
                return ResourceManager.GetString("btnCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string btnCrearAgregarLibro {
            get {
                return ResourceManager.GetString("btnCrearAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string btnCrearAgregarUsuario {
            get {
                return ResourceManager.GetString("btnCrearAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cortohistoria.
        /// </summary>
        internal static string btnCrearCortohistoria {
            get {
                return ResourceManager.GetString("btnCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnCrearEditarLibro {
            get {
                return ResourceManager.GetString("btnCrearEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string btnCS {
            get {
                return ResourceManager.GetString("btnCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnEditarCortohistoria {
            get {
                return ResourceManager.GetString("btnEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cortohistoria.
        /// </summary>
        internal static string btnEditarCortohistoriaAdmin {
            get {
                return ResourceManager.GetString("btnEditarCortohistoriaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistorias que continuar.
        /// </summary>
        internal static string btnEditarCortohistorias {
            get {
                return ResourceManager.GetString("btnEditarCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Libro.
        /// </summary>
        internal static string btnEditarLibroAdmin {
            get {
                return ResourceManager.GetString("btnEditarLibroAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnEditarMiCuenta {
            get {
                return ResourceManager.GetString("btnEditarMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnEditarUsuario {
            get {
                return ResourceManager.GetString("btnEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string btnEditarUsuarioAdmin {
            get {
                return ResourceManager.GetString("btnEditarUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarCortohistoria {
            get {
                return ResourceManager.GetString("btnEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cortohistoria.
        /// </summary>
        internal static string btnEliminarCortohistoriaAdmin {
            get {
                return ResourceManager.GetString("btnEliminarCortohistoriaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarLibro {
            get {
                return ResourceManager.GetString("btnEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Libro.
        /// </summary>
        internal static string btnEliminarLibroAdmin {
            get {
                return ResourceManager.GetString("btnEliminarLibroAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarUsuario {
            get {
                return ResourceManager.GetString("btnEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string btnEliminarUsuarioAdmin {
            get {
                return ResourceManager.GetString("btnEliminarUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string btnLibros {
            get {
                return ResourceManager.GetString("btnLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi carrito.
        /// </summary>
        internal static string btnMiCarrito {
            get {
                return ResourceManager.GetString("btnMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        internal static string btnMiCuenta {
            get {
                return ResourceManager.GetString("btnMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Historial de compras.
        /// </summary>
        internal static string btnMiHistorial {
            get {
                return ResourceManager.GetString("btnMiHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Borradores.
        /// </summary>
        internal static string btnMisBorradores {
            get {
                return ResourceManager.GetString("btnMisBorradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Cortohistorias.
        /// </summary>
        internal static string btnMisCortohistorias {
            get {
                return ResourceManager.GetString("btnMisCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Libros.
        /// </summary>
        internal static string btnMisLibros {
            get {
                return ResourceManager.GetString("btnMisLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string btnPagar {
            get {
                return ResourceManager.GetString("btnPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string btnPagarComprar {
            get {
                return ResourceManager.GetString("btnPagarComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegistrase {
            get {
                return ResourceManager.GetString("btnRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string btnRestablecerContrasenya {
            get {
                return ResourceManager.GetString("btnRestablecerContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string btnSubirCortohistoria {
            get {
                return ResourceManager.GetString("btnSubirCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        internal static string btnUser {
            get {
                return ResourceManager.GetString("btnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALORAR.
        /// </summary>
        internal static string btnValorar {
            get {
                return ResourceManager.GetString("btnValorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver como.
        /// </summary>
        internal static string btnVerComoPDF {
            get {
                return ResourceManager.GetString("btnVerComoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de idioma.
        /// </summary>
        internal static string CaptionCambiarIdioma {
            get {
                return ResourceManager.GetString("CaptionCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string chbAdmin {
            get {
                return ResourceManager.GetString("chbAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string chbAdminAgregarUsuario {
            get {
                return ResourceManager.GetString("chbAdminAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        internal static string chbBaja {
            get {
                return ResourceManager.GetString("chbBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuable.
        /// </summary>
        internal static string chbContinuableEditarCortohistoria {
            get {
                return ResourceManager.GetString("chbContinuableEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir Historia.
        /// </summary>
        internal static string chbContinuarCortohistoria {
            get {
                return ResourceManager.GetString("chbContinuarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizada.
        /// </summary>
        internal static string chbFinalizadaEditarCortohistoria {
            get {
                return ResourceManager.GetString("chbFinalizadaEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vetado.
        /// </summary>
        internal static string chbVetado {
            get {
                return ResourceManager.GetString("chbVetado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistorias.
        /// </summary>
        internal static string cmbCortohistoria {
            get {
                return ResourceManager.GetString("cmbCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string cmbLibro {
            get {
                return ResourceManager.GetString("cmbLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string cmbTodo {
            get {
                return ResourceManager.GetString("cmbTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido abrir la conexion.
        /// </summary>
        internal static string ConexionFallida {
            get {
                return ResourceManager.GetString("ConexionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un correo con la nueva Contraseña, esto puede tardar unos minutos..
        /// </summary>
        internal static string ConfirmacionNuevaContrasenya {
            get {
                return ResourceManager.GetString("ConfirmacionNuevaContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        internal static string ContrasenyaIncorrectaLogin {
            get {
                return ResourceManager.GetString("ContrasenyaIncorrectaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo proporcionado no esta registrado.
        /// </summary>
        internal static string CorreoNoExiste {
            get {
                return ResourceManager.GetString("CorreoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar la imagen: .
        /// </summary>
        internal static string ErrorAgregarImagen {
            get {
                return ResourceManager.GetString("ErrorAgregarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar el PDF: .
        /// </summary>
        internal static string ErrorGenerarPDF {
            get {
                return ResourceManager.GetString("ErrorGenerarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Autor.
        /// </summary>
        internal static string errorProviderAutor {
            get {
                return ResourceManager.GetString("errorProviderAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la contraseña.
        /// </summary>
        internal static string errorProviderContrasenyaLogIn {
            get {
                return ResourceManager.GetString("errorProviderContrasenyaLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la contraseña.
        /// </summary>
        internal static string errorProviderContrasenyaRegistro {
            get {
                return ResourceManager.GetString("errorProviderContrasenyaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el correo.
        /// </summary>
        internal static string errorProviderCorreoRegistro {
            get {
                return ResourceManager.GetString("errorProviderCorreoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la dirección.
        /// </summary>
        internal static string errorProviderDireccionRegistro {
            get {
                return ResourceManager.GetString("errorProviderDireccionRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Id.
        /// </summary>
        internal static string errorProviderID {
            get {
                return ResourceManager.GetString("errorProviderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Isbn.
        /// </summary>
        internal static string errorProviderIsbn {
            get {
                return ResourceManager.GetString("errorProviderIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre.
        /// </summary>
        internal static string errorProviderNombreRegistro {
            get {
                return ResourceManager.GetString("errorProviderNombreRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa  el teléfono.
        /// </summary>
        internal static string errorProviderTelefonoRegistro {
            get {
                return ResourceManager.GetString("errorProviderTelefonoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la Titulo.
        /// </summary>
        internal static string errorProviderTitulo {
            get {
                return ResourceManager.GetString("errorProviderTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Usuario.
        /// </summary>
        internal static string errorProviderUsuarioLogIn {
            get {
                return ResourceManager.GetString("errorProviderUsuarioLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa  el usuario.
        /// </summary>
        internal static string errorProviderUsuarioRegistro {
            get {
                return ResourceManager.GetString("errorProviderUsuarioRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan datos por introducir.
        /// </summary>
        internal static string FaltanDatos {
            get {
                return ResourceManager.GetString("FaltanDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valorar.
        /// </summary>
        internal static string gpbValorarLibro {
            get {
                return ResourceManager.GetString("gpbValorarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha seleccionado imagen.
        /// </summary>
        internal static string ImagenNoSeleccionada {
            get {
                return ResourceManager.GetString("ImagenNoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administradores.
        /// </summary>
        internal static string lblAdministradores {
            get {
                return ResourceManager.GetString("lblAdministradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor:.
        /// </summary>
        internal static string lblAutorAgregarLibro {
            get {
                return ResourceManager.GetString("lblAutorAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor:.
        /// </summary>
        internal static string lblAutorEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblAutorEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor:.
        /// </summary>
        internal static string lblAutorEditarLibro {
            get {
                return ResourceManager.GetString("lblAutorEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOR : .
        /// </summary>
        internal static string lblAutorLibro {
            get {
                return ResourceManager.GetString("lblAutorLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría:.
        /// </summary>
        internal static string lblCategoriaAgregarLibro {
            get {
                return ResourceManager.GetString("lblCategoriaAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría:.
        /// </summary>
        internal static string lblCategoriaEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblCategoriaEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría:.
        /// </summary>
        internal static string lblCategoriaEditarLibro {
            get {
                return ResourceManager.GetString("lblCategoriaEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCV :.
        /// </summary>
        internal static string lblCCV {
            get {
                return ResourceManager.GetString("lblCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblClaveAgregarUsuario {
            get {
                return ResourceManager.GetString("lblClaveAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string lblComentarios {
            get {
                return ResourceManager.GetString("lblComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraMiCuenta {
            get {
                return ResourceManager.GetString("lblContraMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContrasena {
            get {
                return ResourceManager.GetString("lblContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado tu contraseña?.
        /// </summary>
        internal static string lblContrasenaOlvidada {
            get {
                return ResourceManager.GetString("lblContrasenaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContrasenyaEditarUsuario {
            get {
                return ResourceManager.GetString("lblContrasenyaEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string lblCorreoAgregarUsuario {
            get {
                return ResourceManager.GetString("lblCorreoAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string lblCorreoContrasenyaOlvidada {
            get {
                return ResourceManager.GetString("lblCorreoContrasenyaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreoEditarUsuario {
            get {
                return ResourceManager.GetString("lblCorreoEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistoria :.
        /// </summary>
        internal static string lblCortohistoriaCrearCortohistoria {
            get {
                return ResourceManager.GetString("lblCortohistoriaCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunas Cortohistorias.
        /// </summary>
        internal static string lblCortohistoriasEnLibros {
            get {
                return ResourceManager.GetString("lblCortohistoriasEnLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CortoHistorias mas Recientes.
        /// </summary>
        internal static string lblCortohistoriasRecientes {
            get {
                return ResourceManager.GetString("lblCortohistoriasRecientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de tarjeta :.
        /// </summary>
        internal static string lblDatosDeTarjeta {
            get {
                return ResourceManager.GetString("lblDatosDeTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Usuario.
        /// </summary>
        internal static string lblDatosDeUsuario {
            get {
                return ResourceManager.GetString("lblDatosDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lblDireccionAgregarUsuario {
            get {
                return ResourceManager.GetString("lblDireccionAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lblDireccionEditarUsuario {
            get {
                return ResourceManager.GetString("lblDireccionEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string lblDireccionMiCuenta {
            get {
                return ResourceManager.GetString("lblDireccionMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione cual quiere continuar( doble click).
        /// </summary>
        internal static string lblDobleClickSeleccionarCH {
            get {
                return ResourceManager.GetString("lblDobleClickSeleccionarCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplares :.
        /// </summary>
        internal static string lblEjemplaresLibro {
            get {
                return ResourceManager.GetString("lblEjemplaresLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErrorEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblErrorEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErrorEditarUsuario {
            get {
                return ResourceManager.GetString("lblErrorEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresAgregarLibro {
            get {
                return ResourceManager.GetString("lblErroresAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresAgregarUsuario {
            get {
                return ResourceManager.GetString("lblErroresAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresBuscarCortohistoria {
            get {
                return ResourceManager.GetString("lblErroresBuscarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresBuscarLibro {
            get {
                return ResourceManager.GetString("lblErroresBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresBuscarUsuario {
            get {
                return ResourceManager.GetString("lblErroresBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string lblErroresEditarLibro {
            get {
                return ResourceManager.GetString("lblErroresEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblErroresEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarLibro {
            get {
                return ResourceManager.GetString("lblErroresEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarUsuario {
            get {
                return ResourceManager.GetString("lblErroresEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de caducidad :.
        /// </summary>
        internal static string lblFechaCaducidad {
            get {
                return ResourceManager.GetString("lblFechaCaducidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Publicación:.
        /// </summary>
        internal static string lblFechaPublicacionEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblFechaPublicacionEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Cortohistoria:.
        /// </summary>
        internal static string lblIdBuscarCortohistoria {
            get {
                return ResourceManager.GetString("lblIdBuscarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id:.
        /// </summary>
        internal static string lblIdEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblIdEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID:.
        /// </summary>
        internal static string lblIdEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblIdEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Usuario:.
        /// </summary>
        internal static string lblIdUsuarioEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblIdUsuarioEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe Total : .
        /// </summary>
        internal static string lblImporteMiCarrito {
            get {
                return ResourceManager.GetString("lblImporteMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe total : .
        /// </summary>
        internal static string lblImporteTotal {
            get {
                return ResourceManager.GetString("lblImporteTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Carácteres: 150.
        /// </summary>
        internal static string lblInfoSinopsisAgregarLibro {
            get {
                return ResourceManager.GetString("lblInfoSinopsisAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Caracteres: 150.
        /// </summary>
        internal static string lblInfoSinopsisEditarLibro {
            get {
                return ResourceManager.GetString("lblInfoSinopsisEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN:.
        /// </summary>
        internal static string lblIsbnAgregarLibro {
            get {
                return ResourceManager.GetString("lblIsbnAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN:.
        /// </summary>
        internal static string lblIsbnBuscarLibro {
            get {
                return ResourceManager.GetString("lblIsbnBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN:.
        /// </summary>
        internal static string lblISBNEditarLibro {
            get {
                return ResourceManager.GetString("lblISBNEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN.
        /// </summary>
        internal static string lblIsbnEliminarLibro {
            get {
                return ResourceManager.GetString("lblIsbnEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos libros :.
        /// </summary>
        internal static string lblLibrosEnCortohistorias {
            get {
                return ResourceManager.GetString("lblLibrosEnCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor valorados por los usuarios :.
        /// </summary>
        internal static string lblMejorValoradosCortoHistoria {
            get {
                return ResourceManager.GetString("lblMejorValoradosCortoHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor valorados por los usuarios:.
        /// </summary>
        internal static string lblMejorvaloradosLibros {
            get {
                return ResourceManager.GetString("lblMejorvaloradosLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Libro.
        /// </summary>
        internal static string lblMensajeAgregarLibro {
            get {
                return ResourceManager.GetString("lblMensajeAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Usuario.
        /// </summary>
        internal static string lblMensajeAgregarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Cortohistoria.
        /// </summary>
        internal static string lblMensajeBuscarCortohistoria {
            get {
                return ResourceManager.GetString("lblMensajeBuscarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Libro.
        /// </summary>
        internal static string lblMensajeBuscarLibro {
            get {
                return ResourceManager.GetString("lblMensajeBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Usuario.
        /// </summary>
        internal static string lblMensajeBuscarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cortohistoria.
        /// </summary>
        internal static string lblMensajeEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblMensajeEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Libro.
        /// </summary>
        internal static string lblMensajeEditarLibro {
            get {
                return ResourceManager.GetString("lblMensajeEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string lblMensajeEditarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cortohistoria.
        /// </summary>
        internal static string lblMensajeEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblMensajeEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Libro.
        /// </summary>
        internal static string lblMensajeEliminarLibro {
            get {
                return ResourceManager.GetString("lblMensajeEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string lblMensajeEliminarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensajes de Error.
        /// </summary>
        internal static string lblMensajesError {
            get {
                return ResourceManager.GetString("lblMensajesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lblNombreAgregarUsuario {
            get {
                return ResourceManager.GetString("lblNombreAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombreEditarUsuario {
            get {
                return ResourceManager.GetString("lblNombreEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lblNombreMiCuenta {
            get {
                return ResourceManager.GetString("lblNombreMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero tarjeta :.
        /// </summary>
        internal static string lblNumeroTarjeta {
            get {
                return ResourceManager.GetString("lblNumeroTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecioAgregarLibro {
            get {
                return ResourceManager.GetString("lblPrecioAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecioEditarLibro {
            get {
                return ResourceManager.GetString("lblPrecioEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendados por Litterium :.
        /// </summary>
        internal static string lblRecomendadosCortohistorias {
            get {
                return ResourceManager.GetString("lblRecomendadosCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendados por Litterium:.
        /// </summary>
        internal static string lblRecomendadosLitterium {
            get {
                return ResourceManager.GetString("lblRecomendadosLitterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string lblRegistrase {
            get {
                return ResourceManager.GetString("lblRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESULTADOS.
        /// </summary>
        internal static string lblResultadosBusqueda {
            get {
                return ResourceManager.GetString("lblResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis.
        /// </summary>
        internal static string lblSinopsis {
            get {
                return ResourceManager.GetString("lblSinopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis:.
        /// </summary>
        internal static string lblSinopsisAgregarLibro {
            get {
                return ResourceManager.GetString("lblSinopsisAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis:.
        /// </summary>
        internal static string lblSinopsisEditarLibro {
            get {
                return ResourceManager.GetString("lblSinopsisEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string lblTelefonoAgregarUsuario {
            get {
                return ResourceManager.GetString("lblTelefonoAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string lblTelefonoEditarUsuario {
            get {
                return ResourceManager.GetString("lblTelefonoEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono:.
        /// </summary>
        internal static string lblTeléfonoMiCuenta {
            get {
                return ResourceManager.GetString("lblTeléfonoMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No te has registrado aún?.
        /// </summary>
        internal static string lblTextoRegistrase {
            get {
                return ResourceManager.GetString("lblTextoRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string lblTituloAgregarLibro {
            get {
                return ResourceManager.GetString("lblTituloAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de compra.
        /// </summary>
        internal static string lblTituloComprar {
            get {
                return ResourceManager.GetString("lblTituloComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo :.
        /// </summary>
        internal static string lblTituloCrearCortohistoria {
            get {
                return ResourceManager.GetString("lblTituloCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título:.
        /// </summary>
        internal static string lblTituloEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblTituloEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo:.
        /// </summary>
        internal static string lblTituloEditarLibro {
            get {
                return ResourceManager.GetString("lblTituloEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TITULO :.
        /// </summary>
        internal static string lblTituloLibro {
            get {
                return ResourceManager.GetString("lblTituloLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer Contraseña.
        /// </summary>
        internal static string lblTituloRestablecerContrasenya {
            get {
                return ResourceManager.GetString("lblTituloRestablecerContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo : .
        /// </summary>
        internal static string lblTituloVisulaizarCortohistoria {
            get {
                return ResourceManager.GetString("lblTituloVisulaizarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicacion de la entrega :.
        /// </summary>
        internal static string lblUbicacionEntrega {
            get {
                return ResourceManager.GetString("lblUbicacionEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuarioAgegarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioAgegarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuarioBuscarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuarioEditarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuarioEliminarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuarioMiCuenta {
            get {
                return ResourceManager.GetString("lblUsuarioMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración:.
        /// </summary>
        internal static string lblValoracionAgregarLibro {
            get {
                return ResourceManager.GetString("lblValoracionAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración:.
        /// </summary>
        internal static string lblValoracionEditarCortohistoria {
            get {
                return ResourceManager.GetString("lblValoracionEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración:.
        /// </summary>
        internal static string lblValoracionEditarLibro {
            get {
                return ResourceManager.GetString("lblValoracionEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración : .
        /// </summary>
        internal static string lblValoracionLibro {
            get {
                return ResourceManager.GetString("lblValoracionLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar Cortohistoria de : .
        /// </summary>
        internal static string lblVisualizarCortohistoria {
            get {
                return ResourceManager.GetString("lblVisualizarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El libro ya existe.
        /// </summary>
        internal static string LibroYaExiste {
            get {
                return ResourceManager.GetString("LibroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro que quieres cambiar de idioma? (Se le redirigirá al menú principal).
        /// </summary>
        internal static string MensajeCambiarIdioma {
            get {
                return ResourceManager.GetString("MensajeCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el ID.
        /// </summary>
        internal static string NoExisteID {
            get {
                return ResourceManager.GetString("NoExisteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ISBN no existe.
        /// </summary>
        internal static string NoExisteISBN {
            get {
                return ResourceManager.GetString("NoExisteISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe.
        /// </summary>
        internal static string NoExisteUsuario {
            get {
                return ResourceManager.GetString("NoExisteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo añadido al carrito correctamente.
        /// </summary>
        internal static string ObjetoAlCarrito {
            get {
                return ResourceManager.GetString("ObjetoAlCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para cambiar su contraseña haga click en este enlace:.
        /// </summary>
        internal static string ParaCambiarContrasenya {
            get {
                return ResourceManager.GetString("ParaCambiarContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COPIA FISICA.
        /// </summary>
        internal static string rbtCopiaFisica {
            get {
                return ResourceManager.GetString("rbtCopiaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COPIA ONLINE.
        /// </summary>
        internal static string rbtCopiaOnline {
            get {
                return ResourceManager.GetString("rbtCopiaOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al activar esta funcion permites que el resto de usuarios puedan continuar la cortohistoria..
        /// </summary>
        internal static string SeguirCortoHistoriaToolTip {
            get {
                return ResourceManager.GetString("SeguirCortoHistoriaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración Cortohistoria.
        /// </summary>
        internal static string TituloAdministracionCortohistoria {
            get {
                return ResourceManager.GetString("TituloAdministracionCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración Libro.
        /// </summary>
        internal static string TituloAdministracionLibro {
            get {
                return ResourceManager.GetString("TituloAdministracionLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración Usuario.
        /// </summary>
        internal static string TituloAdministracionUsuario {
            get {
                return ResourceManager.GetString("TituloAdministracionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Libro.
        /// </summary>
        internal static string TituloAgregarLibro {
            get {
                return ResourceManager.GetString("TituloAgregarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Usuario.
        /// </summary>
        internal static string TituloAgregarUsuario {
            get {
                return ResourceManager.GetString("TituloAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Cortohistoria.
        /// </summary>
        internal static string TituloBuscarCortohistoria {
            get {
                return ResourceManager.GetString("TituloBuscarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Libro.
        /// </summary>
        internal static string TituloBuscarLibro {
            get {
                return ResourceManager.GetString("TituloBuscarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Usuario.
        /// </summary>
        internal static string TituloBuscarUsuario {
            get {
                return ResourceManager.GetString("TituloBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        internal static string TituloBusqueda {
            get {
                return ResourceManager.GetString("TituloBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string TituloComprar {
            get {
                return ResourceManager.GetString("TituloComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña olvidada.
        /// </summary>
        internal static string TituloContrasenyaOlvidada {
            get {
                return ResourceManager.GetString("TituloContrasenyaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistoria Principal.
        /// </summary>
        internal static string TituloCortohistoriaPrincipal {
            get {
                return ResourceManager.GetString("TituloCortohistoriaPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cortohistoria.
        /// </summary>
        internal static string TituloCrearCortohistoria {
            get {
                return ResourceManager.GetString("TituloCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cortohistoria.
        /// </summary>
        internal static string TituloEditarCortohistoria {
            get {
                return ResourceManager.GetString("TituloEditarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Libro.
        /// </summary>
        internal static string TituloEditarLibro {
            get {
                return ResourceManager.GetString("TituloEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string TituloEditarUsuario {
            get {
                return ResourceManager.GetString("TituloEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cortohistoria.
        /// </summary>
        internal static string TituloEliminarCortohistoria {
            get {
                return ResourceManager.GetString("TituloEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Libro.
        /// </summary>
        internal static string TituloEliminarLibro {
            get {
                return ResourceManager.GetString("TituloEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string TituloEliminarUsuario {
            get {
                return ResourceManager.GetString("TituloEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial Compras.
        /// </summary>
        internal static string TituloHistorialComprar {
            get {
                return ResourceManager.GetString("TituloHistorialComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Libro.
        /// </summary>
        internal static string TituloInformacionLibro {
            get {
                return ResourceManager.GetString("TituloInformacionLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal Libros.
        /// </summary>
        internal static string TituloLibroPrincipal {
            get {
                return ResourceManager.GetString("TituloLibroPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Cortohistorias Continuar.
        /// </summary>
        internal static string TituloListaCortohistoriasContinuar {
            get {
                return ResourceManager.GetString("TituloListaCortohistoriasContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string TituloLogin {
            get {
                return ResourceManager.GetString("TituloLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Administrador.
        /// </summary>
        internal static string TituloMenuAdministrador {
            get {
                return ResourceManager.GetString("TituloMenuAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        internal static string TituloMenuPrincipal {
            get {
                return ResourceManager.GetString("TituloMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Usuario.
        /// </summary>
        internal static string TituloMenuUsuario {
            get {
                return ResourceManager.GetString("TituloMenuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Carrito.
        /// </summary>
        internal static string TituloMiCarrito {
            get {
                return ResourceManager.GetString("TituloMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        internal static string TituloMiCuenta {
            get {
                return ResourceManager.GetString("TituloMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Borradores.
        /// </summary>
        internal static string TituloMisBorradores {
            get {
                return ResourceManager.GetString("TituloMisBorradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Cortohistorias.
        /// </summary>
        internal static string TituloMisCortohistorias {
            get {
                return ResourceManager.GetString("TituloMisCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Libros.
        /// </summary>
        internal static string TituloMisLibros {
            get {
                return ResourceManager.GetString("TituloMisLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string TituloRegistro {
            get {
                return ResourceManager.GetString("TituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar Cortohistoria.
        /// </summary>
        internal static string TituloVisualizarCortohistoria {
            get {
                return ResourceManager.GetString("TituloVisualizarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu nueva contraseña es: .
        /// </summary>
        internal static string TuNuevaContrasenya {
            get {
                return ResourceManager.GetString("TuNuevaContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe.
        /// </summary>
        internal static string UsuarioNoExisteLogin {
            get {
                return ResourceManager.GetString("UsuarioNoExisteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya existe.
        /// </summary>
        internal static string UsuarioYaExisteRegistro {
            get {
                return ResourceManager.GetString("UsuarioYaExisteRegistro", resourceCulture);
            }
        }
    }
}
