//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registro_mockup.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogIn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogIn() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("registro_mockup.Idiomas.LogIn", typeof(LogIn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion CortoHistoria.
        /// </summary>
        internal static string btnAC {
            get {
                return ResourceManager.GetString("btnAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion Libro.
        /// </summary>
        internal static string btnAL {
            get {
                return ResourceManager.GetString("btnAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AÑADIR AL CARRITO.
        /// </summary>
        internal static string btnAñadirCarrito {
            get {
                return ResourceManager.GetString("btnAñadirCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion Usuario.
        /// </summary>
        internal static string btnAU {
            get {
                return ResourceManager.GetString("btnAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borradores.
        /// </summary>
        internal static string btnBorradoresCortohistorias {
            get {
                return ResourceManager.GetString("btnBorradoresCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btnBorrar {
            get {
                return ResourceManager.GetString("btnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnCargarEditarLibro {
            get {
                return ResourceManager.GetString("btnCargarEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        internal static string btnCargarImagenEditarUsuario {
            get {
                return ResourceManager.GetString("btnCargarImagenEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPRAR AHORA.
        /// </summary>
        internal static string btnComprarAhora {
            get {
                return ResourceManager.GetString("btnComprarAhora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistorias.
        /// </summary>
        internal static string btnCortohistorias {
            get {
                return ResourceManager.GetString("btnCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnCrearEditarLibro {
            get {
                return ResourceManager.GetString("btnCrearEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string btnCS {
            get {
                return ResourceManager.GetString("btnCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string btnEditarUsuario {
            get {
                return ResourceManager.GetString("btnEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarCortohistoria {
            get {
                return ResourceManager.GetString("btnEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarLibro {
            get {
                return ResourceManager.GetString("btnEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminarUsuario {
            get {
                return ResourceManager.GetString("btnEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string btnLibros {
            get {
                return ResourceManager.GetString("btnLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi carrito.
        /// </summary>
        internal static string btnMiCarrito {
            get {
                return ResourceManager.GetString("btnMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        internal static string btnMiCuenta {
            get {
                return ResourceManager.GetString("btnMiCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Historial de compras.
        /// </summary>
        internal static string btnMiHistorial {
            get {
                return ResourceManager.GetString("btnMiHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Borradores.
        /// </summary>
        internal static string btnMisBorradores {
            get {
                return ResourceManager.GetString("btnMisBorradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Cortohistorias.
        /// </summary>
        internal static string btnMisCortohistorias {
            get {
                return ResourceManager.GetString("btnMisCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Libros.
        /// </summary>
        internal static string btnMisLibros {
            get {
                return ResourceManager.GetString("btnMisLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string btnPagar {
            get {
                return ResourceManager.GetString("btnPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string btnPagarComprar {
            get {
                return ResourceManager.GetString("btnPagarComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegistrase {
            get {
                return ResourceManager.GetString("btnRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string btnRestablecerContrasenya {
            get {
                return ResourceManager.GetString("btnRestablecerContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir.
        /// </summary>
        internal static string btnSubirCortohistoria {
            get {
                return ResourceManager.GetString("btnSubirCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        internal static string btnUser {
            get {
                return ResourceManager.GetString("btnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string chbAdmin {
            get {
                return ResourceManager.GetString("chbAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja.
        /// </summary>
        internal static string chbBaja {
            get {
                return ResourceManager.GetString("chbBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir Historia.
        /// </summary>
        internal static string chbContinuarCortohistoria {
            get {
                return ResourceManager.GetString("chbContinuarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vetado.
        /// </summary>
        internal static string chbVetado {
            get {
                return ResourceManager.GetString("chbVetado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistorias.
        /// </summary>
        internal static string cmbCortohistoria {
            get {
                return ResourceManager.GetString("cmbCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libros.
        /// </summary>
        internal static string cmbLibro {
            get {
                return ResourceManager.GetString("cmbLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string cmbTodo {
            get {
                return ResourceManager.GetString("cmbTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administradores.
        /// </summary>
        internal static string lblAdministradores {
            get {
                return ResourceManager.GetString("lblAdministradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor:.
        /// </summary>
        internal static string lblAutorEditarLibro {
            get {
                return ResourceManager.GetString("lblAutorEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOR : .
        /// </summary>
        internal static string lblAutorLibro {
            get {
                return ResourceManager.GetString("lblAutorLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría:.
        /// </summary>
        internal static string lblCategoriaEditarLibro {
            get {
                return ResourceManager.GetString("lblCategoriaEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CCV :.
        /// </summary>
        internal static string lblCCV {
            get {
                return ResourceManager.GetString("lblCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        internal static string lblComentarios {
            get {
                return ResourceManager.GetString("lblComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContrasena {
            get {
                return ResourceManager.GetString("lblContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Has olvidado tu contraseña?.
        /// </summary>
        internal static string lblContrasenaOlvidada {
            get {
                return ResourceManager.GetString("lblContrasenaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContrasenyaEditarUsuario {
            get {
                return ResourceManager.GetString("lblContrasenyaEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string lblCorreoContrasenyaOlvidada {
            get {
                return ResourceManager.GetString("lblCorreoContrasenyaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreoEditarUsuario {
            get {
                return ResourceManager.GetString("lblCorreoEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistoria :.
        /// </summary>
        internal static string lblCortohistoriaCrearCortohistoria {
            get {
                return ResourceManager.GetString("lblCortohistoriaCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunas Cortohistorias.
        /// </summary>
        internal static string lblCortohistoriasEnLibros {
            get {
                return ResourceManager.GetString("lblCortohistoriasEnLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de tarjeta :.
        /// </summary>
        internal static string lblDatosDeTarjeta {
            get {
                return ResourceManager.GetString("lblDatosDeTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Usuario.
        /// </summary>
        internal static string lblDatosDeUsuario {
            get {
                return ResourceManager.GetString("lblDatosDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string lblDireccionEditarUsuario {
            get {
                return ResourceManager.GetString("lblDireccionEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplares :.
        /// </summary>
        internal static string lblEjemplaresLibro {
            get {
                return ResourceManager.GetString("lblEjemplaresLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErrorEditarUsuario {
            get {
                return ResourceManager.GetString("lblErrorEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string lblErroresEditarLibro {
            get {
                return ResourceManager.GetString("lblErroresEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblErroresEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarLibro {
            get {
                return ResourceManager.GetString("lblErroresEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Error.
        /// </summary>
        internal static string lblErroresEliminarUsuario {
            get {
                return ResourceManager.GetString("lblErroresEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de caducidad :.
        /// </summary>
        internal static string lblFechaCaducidad {
            get {
                return ResourceManager.GetString("lblFechaCaducidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID:.
        /// </summary>
        internal static string lblIdEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblIdEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe Total : .
        /// </summary>
        internal static string lblImporteMiCarrito {
            get {
                return ResourceManager.GetString("lblImporteMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe total : 0,00€.
        /// </summary>
        internal static string lblImporteTotal {
            get {
                return ResourceManager.GetString("lblImporteTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Caracteres: 150.
        /// </summary>
        internal static string lblInfoSinopsisEditarLibro {
            get {
                return ResourceManager.GetString("lblInfoSinopsisEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN:.
        /// </summary>
        internal static string lblISBNEditarLibro {
            get {
                return ResourceManager.GetString("lblISBNEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISBN.
        /// </summary>
        internal static string lblIsbnEliminarLibro {
            get {
                return ResourceManager.GetString("lblIsbnEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos libros :.
        /// </summary>
        internal static string lblLibrosEnCortohistorias {
            get {
                return ResourceManager.GetString("lblLibrosEnCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor valorados por los usuarios :.
        /// </summary>
        internal static string lblMejorValoradosCortoHistoria {
            get {
                return ResourceManager.GetString("lblMejorValoradosCortoHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor valorados por los usuarios:.
        /// </summary>
        internal static string lblMejorvaloradosLibros {
            get {
                return ResourceManager.GetString("lblMejorvaloradosLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Libro.
        /// </summary>
        internal static string lblMensajeEditarLibro {
            get {
                return ResourceManager.GetString("lblMensajeEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string lblMensajeEditarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cortohistoria.
        /// </summary>
        internal static string lblMensajeEliminarCortohistoria {
            get {
                return ResourceManager.GetString("lblMensajeEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Libro.
        /// </summary>
        internal static string lblMensajeEliminarLibro {
            get {
                return ResourceManager.GetString("lblMensajeEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string lblMensajeEliminarUsuario {
            get {
                return ResourceManager.GetString("lblMensajeEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensajes de Error.
        /// </summary>
        internal static string lblMensajesError {
            get {
                return ResourceManager.GetString("lblMensajesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombreEditarUsuario {
            get {
                return ResourceManager.GetString("lblNombreEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero tarjeta :.
        /// </summary>
        internal static string lblNumeroTarjeta {
            get {
                return ResourceManager.GetString("lblNumeroTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecioEditarLibro {
            get {
                return ResourceManager.GetString("lblPrecioEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendados por Litterium :.
        /// </summary>
        internal static string lblRecomendadosCortohistorias {
            get {
                return ResourceManager.GetString("lblRecomendadosCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendados por Litterium:.
        /// </summary>
        internal static string lblRecomendadosLitterium {
            get {
                return ResourceManager.GetString("lblRecomendadosLitterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string lblRegistrase {
            get {
                return ResourceManager.GetString("lblRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESULTADOS.
        /// </summary>
        internal static string lblResultadosBusqueda {
            get {
                return ResourceManager.GetString("lblResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis.
        /// </summary>
        internal static string lblSinopsis {
            get {
                return ResourceManager.GetString("lblSinopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sinopsis:.
        /// </summary>
        internal static string lblSinopsisEditarLibro {
            get {
                return ResourceManager.GetString("lblSinopsisEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTelefonoEditarUsuario {
            get {
                return ResourceManager.GetString("lblTelefonoEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No te has registrado aún?.
        /// </summary>
        internal static string lblTextoRegistrase {
            get {
                return ResourceManager.GetString("lblTextoRegistrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de compra.
        /// </summary>
        internal static string lblTituloComprar {
            get {
                return ResourceManager.GetString("lblTituloComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo :.
        /// </summary>
        internal static string lblTituloCrearCortohistoria {
            get {
                return ResourceManager.GetString("lblTituloCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo:.
        /// </summary>
        internal static string lblTituloEditarLibro {
            get {
                return ResourceManager.GetString("lblTituloEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TITULO :.
        /// </summary>
        internal static string lblTituloLibro {
            get {
                return ResourceManager.GetString("lblTituloLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer Contraseña.
        /// </summary>
        internal static string lblTituloRestablecerContrasenya {
            get {
                return ResourceManager.GetString("lblTituloRestablecerContrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo : .
        /// </summary>
        internal static string lblTituloVisulaizarCortohistoria {
            get {
                return ResourceManager.GetString("lblTituloVisulaizarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicacion de la entrega :.
        /// </summary>
        internal static string lblUbicacionEntrega {
            get {
                return ResourceManager.GetString("lblUbicacionEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuarioEditarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuarioEliminarUsuario {
            get {
                return ResourceManager.GetString("lblUsuarioEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración:.
        /// </summary>
        internal static string lblValoracionEditarLibro {
            get {
                return ResourceManager.GetString("lblValoracionEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración : .
        /// </summary>
        internal static string lblValoracionLibro {
            get {
                return ResourceManager.GetString("lblValoracionLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar Cortohistoria de : .
        /// </summary>
        internal static string lblVisualizarCortohistoria {
            get {
                return ResourceManager.GetString("lblVisualizarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COPIA FISICA.
        /// </summary>
        internal static string rbtCopiaFisica {
            get {
                return ResourceManager.GetString("rbtCopiaFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COPIA ONLINE.
        /// </summary>
        internal static string rbtCopiaOnline {
            get {
                return ResourceManager.GetString("rbtCopiaOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        internal static string TituloBusqueda {
            get {
                return ResourceManager.GetString("TituloBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string TituloComprar {
            get {
                return ResourceManager.GetString("TituloComprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña olvidada.
        /// </summary>
        internal static string TituloContrasenyaOlvidada {
            get {
                return ResourceManager.GetString("TituloContrasenyaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortohistoria Principal.
        /// </summary>
        internal static string TituloCortohistoriaPrincipal {
            get {
                return ResourceManager.GetString("TituloCortohistoriaPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cortohistoria.
        /// </summary>
        internal static string TituloCrearCortohistoria {
            get {
                return ResourceManager.GetString("TituloCrearCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Libro.
        /// </summary>
        internal static string TituloEditarLibro {
            get {
                return ResourceManager.GetString("TituloEditarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string TituloEditarUsuario {
            get {
                return ResourceManager.GetString("TituloEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Cortohistoria.
        /// </summary>
        internal static string TituloEliminarCortohistoria {
            get {
                return ResourceManager.GetString("TituloEliminarCortohistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Libro.
        /// </summary>
        internal static string TituloEliminarLibro {
            get {
                return ResourceManager.GetString("TituloEliminarLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string TituloEliminarUsuario {
            get {
                return ResourceManager.GetString("TituloEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Libro.
        /// </summary>
        internal static string TituloInformacionLibro {
            get {
                return ResourceManager.GetString("TituloInformacionLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal Libros.
        /// </summary>
        internal static string TituloLibroPrincipal {
            get {
                return ResourceManager.GetString("TituloLibroPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string TituloLogin {
            get {
                return ResourceManager.GetString("TituloLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Administrador.
        /// </summary>
        internal static string TituloMenuAdministrador {
            get {
                return ResourceManager.GetString("TituloMenuAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        internal static string TituloMenuPrincipal {
            get {
                return ResourceManager.GetString("TituloMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Usuario.
        /// </summary>
        internal static string TituloMenuUsuario {
            get {
                return ResourceManager.GetString("TituloMenuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Carrito.
        /// </summary>
        internal static string TituloMiCarrito {
            get {
                return ResourceManager.GetString("TituloMiCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Borradores.
        /// </summary>
        internal static string TituloMisBorradores {
            get {
                return ResourceManager.GetString("TituloMisBorradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Cortohistorias.
        /// </summary>
        internal static string TituloMisCortohistorias {
            get {
                return ResourceManager.GetString("TituloMisCortohistorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Libros.
        /// </summary>
        internal static string TituloMisLibros {
            get {
                return ResourceManager.GetString("TituloMisLibros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string TituloRegistro {
            get {
                return ResourceManager.GetString("TituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizar Cortohistoria.
        /// </summary>
        internal static string TituloVisualizarCortohistoria {
            get {
                return ResourceManager.GetString("TituloVisualizarCortohistoria", resourceCulture);
            }
        }
    }
}
